### PR TITLE
Widen PHP support

### PR DESCRIPTION
**Pull request by juliangut**
I know PHP 7.2 is already EOL but hear me out

This PR widens PHP support for the formatter to match requested PHPStan version 1.12.4, which supports PHP ^7.2|^8.0
The updates are the absolute minimum necessary to allow PHP 7.2 support, no behaviour is altered, added or removed

Given supported PHPStan version supports 7.2 I think this PR could be a reasonable change

### CODE REVIEW

**Comment by ruudk** [comment]
Could you setup a CI matrix that tests all versions?

**Comment by ruudk** [comment]
Thanks.

Do you think it would be good to also include a unit test? If you're up to it that would be great. 🙌

**Comment by ruudk** [comment]
@juliangut would you be up for that?

**Comment by juliangut** [comment]
sorry, at this moment I was interested only on the PHP version support, don't think I have the time to create a test suite but I think it's a good idea of course

**Pull request merged**
