### PR TITLE
Revert PHP 7.2 support and require at least 8.1

### PR DESCRIPTION
**Pull request by ruudk**
@juliangut I thought about your change #10, and decided to undo it. The reason for this is that PHPStan 2.0 is in the works, and it will only support 8.1 and higher. Given that is going to be released in the coming months (?) I don't want to struggle with these old unsupported PHP versions.

### CODE REVIEW

**Comment by juliangut** [comment]
I understand the reasoning behind PHPStan 2* supported versions in the near future, but I'd point out it is exactly the same point I made about PHPStan 1* supported versions now. It's a pity there will not be a version of this package with support for what PHPStan 1* supports

**Comment by ruudk** [comment]
Do you have a specific use case where this is a problem? Or is this a theoretical problem?

**Comment by ruudk** [comment]
According to https://github.com/phpstan/phpstan/issues/4060#issuecomment-723559902 you only have to run PHPStan twice, on PHP 7 and PHP 8. That means it could run on PHP 7.4 and 8.x. That would make it a little bit easier, as then we can get typed properties and such.

**Comment by juliangut** [comment]
I'm currently working on a 7.3/7.4 codebase which won't be updated in the near future to 8* so I'm stuck in this project with PHPStan 1* in the foreseeable future. There are many legacy codebase that are not being updated and developers on those codebase, but we all can benefit greatly from PHPStan in any version, and we could benefit from this  formatter as well

**Comment by ruudk** [comment]
So what if we lower it to PHP 7.4 then?

**Comment by juliangut** [comment]
I thought so at the beginning, then I had a look at PHPStan version supported (1.12.4) and I saw they support 7.2 and so I dive deeper

**Comment by ruudk** [comment]
Ok, let's see what this brings: https://github.com/TicketSwap/phpstan-error-formatter/pull/15

**Comment by ruudk** [comment]
@juliangut Done, see https://github.com/TicketSwap/phpstan-error-formatter/releases/tag/1.1.2

**Comment by juliangut** [comment]
Great 👍🏾

**Pull request merged**
